-- TESTANDO MIGRATION COM FLYWAY

CREATE TABLE tb_administrador (
	PK_IDAdmin BIGINT(10) PRIMARY KEY AUTO_INCREMENT,
	CK_matricula VARCHAR(6) NOT NULL UNIQUE,
	cargo VARCHAR(120),
	nome VARCHAR(150),
	email VARCHAR(100) UNIQUE
	);
